"""
Quote Validator.

Validates that quotes generated by the LLM are exact substrings of the original review bodies.
Drops invalid quotes and logs metrics.
"""

from __future__ import annotations

import structlog

from src.analysis.models import Theme
from src.ingestion.models import Review

logger = structlog.get_logger(__name__)


def validate_quotes(theme: Theme, original_reviews: list[Review]) -> Theme:
    """
    Validate that all quotes in the Theme appear in the original reviews.
    Modifies the Theme in-place (updates Quote.validated and drops invalid ones).
    """
    valid_quotes = []

    # Pre-process review bodies for faster checking
    # (Just exact matches for now, as specified in the plan)
    review_texts = [r.body for r in original_reviews if r.body]

    for quote in theme.quotes:
        quote_text = quote.text.strip()

        # Check if the exact quote is a substring of any review
        is_valid = any(quote_text in text for text in review_texts)

        if is_valid:
            quote.validated = True
            valid_quotes.append(quote)
        else:
            logger.debug(
                "quote_validation_failed",
                theme_name=theme.name,
                quote=quote_text,
            )

    # Calculate metrics
    proposed = len(theme.quotes)
    validated = len(valid_quotes)

    if proposed > 0:
        validation_rate = validated / proposed
        if validation_rate < 0.5:
            logger.warning(
                "low_quote_validation_rate",
                theme_name=theme.name,
                proposed=proposed,
                validated=validated,
                rate=validation_rate,
            )

    # Keep only valid quotes
    theme.quotes = valid_quotes
    return theme
